	private void assertTransportException(ThrowingCallable c,
			String messageContent) throws AssertionError {
		assertThat(catchThrowableOfType(c, TransportException.class))
				.hasMessageContaining(messageContent);
	}

